Test DBpedia URI to Wiki URL
nestauk/dap_dv_backends pull request #105
Opened 2022-05-10 12:36 UTC by doogyb

Added tests to see if we get 200 responses from using simple string
manipulation on the DBpedia URis.

closes #104

2022-06-13 11:17 UTC, mindrones requested changes
1st pass

2022-06-13 11:17 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +import { saveObj } from '@svizzle/file';
npm import to be with the other ones and sorted by package id

2022-06-13 11:17 UTC, mindrones commented on src/node_modules/dbpedia/requests.mjs
> +export const getDetails = async input => {
I'd rename it to `getEntityDetails`

2022-06-13 11:17 UTC, mindrones commented on src/node_modules/wiki/page.mjs
> +import { fetch } from 'undici';
I'd rename the dir to `wikipedia`

2022-06-13 11:17 UTC, mindrones commented on src/node_modules/wiki/page.mjs
> +}
leftovers I think :)

2022-06-13 11:17 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +describe('dbpedia', () => {
I'd use an id specific to the AI map

2022-06-13 11:17 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +			bar.stop();
I'd move these lines to an async function that we can reuse.

We should also check that it worked (as in "succesfully retrieved details"), with saving being a side-effect, or we could just change the test subject.

2022-06-13 11:17 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +			}, {});
I'd prefer we don't use `_.mapValues` without a return value.

I think we could use something like:

```suggestion
			const counts = _.reduce(details, (acc, curr) => {
				const ones = _.mapValues(curr, _.always(1));
				const newAcc = mergeWithSum(acc, ones);

				return newAcc;
			}, {});
```

2022-06-13 11:17 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +		it('tests the number of missing details', function() {
I'd change the subject to something like `'retrieve the number of missing details'`, because we're not actually checking the numbers in this test

2022-06-13 11:17 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +			const thumbnails = _.map(
(1) I'd rename `thumbnails` to `thumbnailURLs`

2022-06-13 11:17 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +			}, {});
(2) I'd use `_.count` here

2022-06-13 11:17 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +			console.log(counts);
it would be useful to log these counts in a file

2022-06-13 11:17 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +const FILE_LOG = 'data/ai_map/test/URIs_details.json';
I'd rename `FILE_LOG` to `FILE_DETAILS` or so

2022-06-13 11:17 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +			const thumbnails = _.map(
See (1)

2022-06-13 11:17 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +				}
See (2)

2022-06-13 11:17 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +const FILE_DBPEDIA_URIS = 'data/ai_map/test/URI_titles.json';
I'd use 
```suggestion
const FILE_DBPEDIA_URIS = 'data/ai_map/test/URIs.json';
```

2022-06-13 11:17 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +const getTitles = async () => {
I'd use get "id" everywhere here instead of "title"

2022-06-13 12:34 UTC, doogyb commented on src/node_modules/wiki/page.mjs
> +import { fetch } from 'undici';
The API itself is `wikimedia` and it seems most of the products use that prefix so I stuck with `wiki` - what do you think?

2022-06-13 13:29 UTC, doogyb commented on src/test/ai_map.spec.mjs
> +const getTitles = async () => {
The reason I chose `title` here was to distinguish from the actual `id` of a wikipedia page, which is saved numerically. What do you think? There's a 1-1 mapping between the two, but just to be explicit about what kind of resource we're dealing with I used `title`.

2022-06-13 13:31 UTC, doogyb commented on src/test/ai_map.spec.mjs
> +const FILE_DBPEDIA_URIS = 'data/ai_map/test/URI_titles.json';
They're not really URIs though is the only thing because there's no scheme or domain associate with it (`http://dbpedia.org/resource/`)

2022-06-13 14:28 UTC, mindrones reviewed
left some comments below

2022-06-13 14:28 UTC, mindrones commented on src/node_modules/wiki/page.mjs
> +import { fetch } from 'undici';
ah I see, OK

2022-06-13 14:28 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +const FILE_DBPEDIA_URIS = 'data/ai_map/test/URI_titles.json';
Hm, for me a title would be `World War I`, not `World_War_I`.

What about the below?

```
const FILE_DBPEDIA_IDS = 'data/ai_map/test/Dbpedia_IDs.json';
```

2022-06-13 14:28 UTC, mindrones commented on src/test/ai_map.spec.mjs
> +const getTitles = async () => {
Here too, a title for me could be a phrase eventually with spaces, so I'd prefer to use something derived from the word "id".

2022-06-14 11:18 UTC, mindrones approved these changes
GTM 👍

2022-06-14 11:25 UTC, merged